version: '3.8'

services:
  frontend:
    build: .
    container_name: hackathon-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: hackathon-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/db.json:/app/db.json